runtime: nodejs20
instance_class: F2
env_variables:
  NODE_ENV: production
handlers:
  # Serve static files from the dist directory
  - url: /(.*\..+)$
    static_files: dist/\1
    upload: dist/(.*\..+)$

  # Catch-all handler: serve index.html for all other routes
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html